[package]
name = "wshell"
description = "A shell for the browser"
version = "0.0.2"
authors = ["Joshua Unrau <contact@joshuaunrau.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/joshunrau/wshell"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
